### ISSUE TITLE
Run services using docker swarm

### ISSUE THREAD

**Issue by 13angs** [13angs/simple-ecom#6]
## Todos
- [x] run product-sv in docker swarm
- [x] run order-sv in docker swarm
- [x] run gateway-sv in docker swarm
- [x] remove the gateway-sv expose port
- [x] run haproxy in docker swarm
  - create custom haproxy image
  - copy the config file into image 
- [x] remove consul expose port
  - remove port
  - expose consul using haproxy
  - build the haproxy image with no cache
  - rerun the rerun the services and haproxy
- [x] using se-network in development
  - product-sv
  - order-sv
  - comment-sv
  - gatewary-sv
  - consul 
- [x] setup dev ocelot.json
- [x] dockerize comment-sv
- [x] run comment-sv in docker swarm
- [x] run rabbitmq in docker swarm
- [x] expose rabbimq using haproxy

**Comment by 13angs** [comment]
```bash
haproxy_se-haproxy.2.vawsmib4gc2u@node-1    | [WARNING]  (7) : Server webservers/s1 is DOWN, reason: Layer4 timeout, check duration: 2001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
haproxy_se-haproxy.2.vawsmib4gc2u@node-1    | Server webservers/s1 is DOWN, reason: Layer4 timeout, check duration: 2001ms. 0 active and 0 backup servers left. 0 sessions active, 0 requeued, 0 remaining in queue.
haproxy_se-haproxy.2.vawsmib4gc2u@node-1    | [ALERT]    (7) : backend 'webservers' has no server available!
haproxy_se-haproxy.2.vawsmib4gc2u@node-1    | backend webservers has no server available!
haproxy_se-haproxy.2.vawsmib4gc2u@node-1    | Connect from 10.0.0.2:36084 to 10.0.0.130:8405 (stats/HTTP)
haproxy_se-haproxy.1.sl5jjcqwv71v@node-2    | [NOTICE]   (1) : New worker (7) forked
haproxy_se-haproxy.1.sl5jjcqwv71v@node-2    | [NOTICE]   (1) : Loading success.
```

**Comment by 13angs** [comment]
## Running services in Development
1. run the consul
2. run these services
  1. consul
  2. product-sv
  3. order-sv
  4. comment-sv
  5. gateway-sv

**Comment by 13angs** [comment]
## Running services in Production
- run the consul
- run these services using docker-compose.yml
  - consul
  - rabbitmq
  - product-sv
  - order-sv
  - comment-sv
  - gateway-sv 
- use postman to test the api
