### ISSUE TITLE
Change from in-memory to mongodb

### ISSUE THREAD

**Issue by 13angs** [13angs/simple-ecom#9]
# Todos
- [x] convert in-memory db to mongodb
- [x] dockerize the updated services 
- [x] deploy mongo in single cluster

## Convert in-memory db to mongodb
- run the mongodb instance using docker compose
- install package in lib

```bash
dotnet add package MongoDB.Driver
```
- convert model to mongodb scheme
- update appsetting.json
- register the MongodbConfig extension
- setup the mongo connection
- Implement the crud
- Update the controller
- seeding data
- repeat the process for:
  - order-sv
  - comment-sv 

## Dockerize the updated services
- update the environments
- build and push to dockerhub
  - [x] product-sv
  - [x] order-sv
  - [x] comment-sv

## Deploy mongo in cluster
- remove comment-sv expose port
- setup mongodb in docker swarm
  - remove the expose port
  - change network to prod
  - configure volume
  - change the password
  - update the service url
- remove and rerun all the services

## References
1. https://github.com/13angs/my-lovely-cat/blob/startup-proj/infra/compose/db/mongodb/docker-compose.yml
2. https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/generics/generic-interfaces
3. https://github.com/13angs/al_iqraa/blob/main/api/comment/Services/CommentService.cs

**Comment by 13angs** [comment]
```bash
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: ObjectId is not a valid representation for an Int32Serializer.
```

**Comment by 13angs** [comment]
## Sequence
1. run se-mongo-db service

**Comment by 13angs** [comment]
```bash
services.se-mongo-db.volumes.0 type is required
```
